publications:
  - url: https://www.npmjs.com/package/launchdarkly-node-server-sdk-redis
    description: npm

template:
  name: npm
  skip:
    - test  # Running the unit tests would require installing Redis. They've already been run in CI.

documentation:
  githubPages: true
  title: LaunchDarkly Server-Side Node SDK Redis Integration
